# Generated by Django 5.0.4 on 2024-06-07 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_recepie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='recepie/'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recepie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
