# Generated by Django 4.0.10 on 2024-06-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_recepie_img_alter_recepie_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='product.image'),
        ),
    ]
