# Generated by Django 5.0.4 on 2024-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'ثبت شده'), ('2', 'در حال آماده سازی'), ('3', 'آماده'), ('4', 'تحویل داده شده')], default='1'),
        ),
    ]
